version: '3'

services:
  postgresDB:
    image: postgres:15
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - book

  nest_test:
    depends_on:
      - "postgresDB"
    build:
     context: ./
     dockerfile: Dockerfile
    container_name: nest_test
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - book

networks:
  book:
